name: entraid-broker
summary: EntraID Broker for authd
description: |
  Broker that enables OIDC authentication with EntraID group management for authd.
version: git
grade: stable
base: core24
confinement: strict
license: GPL-3.0+

apps:
  entraid-broker:
    command: bin/entraid-broker
    daemon: simple
    slots:
      - dbus-oidc
    plugs:
      - network
      - config-files
    restart-condition: always

slots:
  dbus-oidc:
    interface: dbus
    bus: system
    name: com.ubuntu.authd.EntraIDBroker

plugs:
  config-files:
    interface: system-files
    read:
      - /etc/authd/brokers.d/entraid-broker

parts:
  oidc-broker:
    source: .
    source-type: local
    plugin: go
    go-buildtags: [withmsentraid]
    build-snaps:
      - go
